[package]
name    = "play"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]

[dependencies.ffmpeg]
git = "git://github.com/meh/rust-ffmpeg"

[dependencies.openal]
git = "git://github.com/meh/rust-openal"
